project_id = "bzbxdiaqpbroxhcibtpm"

[functions.render-site]
verify_jwt = false

[functions.analyze-reference]
verify_jwt = true

[functions.wallet-auth]
verify_jwt = false

[functions.manage-project]
verify_jwt = false

[functions.manage-template]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false